let historyData = [
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/1977",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: false,
  },
];
export default historyData;
