let launchesData = [
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
  {
    mission_name: "Apollo",
    rocket_name: "Lorem Ipsum",
    lat: "34.5",
    lng: "36.06",
    launch_date: "13/12/2023",
    planet: "Moon",
    objective: "lorem ipsum dolor",
    upcoming: true,
  },
];
export default launchesData;
