const roles = [
  "Pilot",
  "Command Pilot",
  "Command Module Pilot",
  "Lunar Module Pilot",
  "Docking Module Pilot",
  "Science Pilot",
  "Payload Specialist",
  "Mission Specialist",
  "Flight Director (FLIGHT)",
  "Spacecraft (or “Capsule”) Communicator (CAPCOM)",
  "Flight Dynamics Officer (FDO)",
  "Guidance Procedures Officer (GPO)",
  "Propulsion Engineer (PROP)",
  "Guidance, Navigation, and Controls Systems Engineer (GNC)",
  "Data Processing System Engineer (DPS)",
  "Integrated Communications Officer (INCO)",
  "Russian Interface Operator (RIO)",
  "Ground Controller (GC)",
  "Flight Activities Officer (FAO)",
  "Payloads Officer (PAYLOADS)",
  "Maintenance, Mechanical, Arm, and Crew Systems (MMACS)",
];
export default roles;
