export const planetQuestions = [
  {
    label: "Planet Name",
    type: "text",
    id: "planet_name",
    name: "planet_name",
    placeholder: "Enter planet name",
  },
  {
    label: "Mass",
    type: "text",
    id: "mass",
    name: "mass",
    placeholder: "Enter planet mass",
  },

  {
    label: "Temperature",
    type: "number",
    id: "temperature",
    name: "temperature",
    placeholder: "Enter planet temperature",
  },
  {
    label: "Gravity",
    type: "number",
    id: "gravity",
    name: "gravity",
    placeholder: "Enter planet's gravity",
  },
  {
    label: "Number of Moons",
    type: "text",
    id: "no_of_moons",
    name: "no_of_moons",
    placeholder: "Enter number of moons",
  },
  {
    label: "Rotation Duration",
    type: "text",
    id: "rotation_duration",
    name: "rotation_duration",
    placeholder: "Enter planet's rotational duration",
  },
  {
    label: "Rotational Speed",
    type: "text",
    id: "rotational_speed",
    name: "rotational_speed",
    placeholder: "Enter planet's rotational speed",
  },
  {
    label: "Distance from Earth",
    type: "text",
    id: "distance_from_earth",
    name: "distance_from_earth",
    placeholder: "Enter planet's distance from earth",
  },
  {
    label: "Number of Satellites",
    type: "text",
    id: "no_of_satellites",
    name: "no_of_satellites",
    placeholder: "Enter planet's number of satellites",
  },
  {
    label: "Structure",
    type: "text",
    id: "structure",
    name: "structure",
    placeholder: "Enter planet's structure ",
  },
  // {
  //   label: "Map Image URL",
  //   type: "file",
  //   id: "imgUrl",
  //   name: "imgUrl",
  //   placeholder: "Enter planet image url",
  // },
];
